### ISSUE TITLE
Request to release the corrected version

### ISSUE THREAD

**Issue by St0ne1ee** [kevinhelvig/CAFF-DETR#3]
Why can't I achieve the performance mentioned in the paper using the trained model you mentioned in the Lite version

**Comment by kevinhelvig** [comment]
Hi ! 
Thanks for your question ! Do you have the log file and do you compare with the one released with the script ? 
I obtained this log just by running the training with the code delivered and only parser modifications are needed to run it properly : do you modified more elements and what are the args you used for training ? 
A small variation of performance is always possible (hardware influence etc ...)

**Comment by kevinhelvig** [comment]
I close the issue. The code is now considered "as easy to run as other DETRs" : please don't hesitate to reopen another if there is still another issue to report, with more details (arguments for the run, log files ... etc). As said, limited variation of performance can still occur, and a difference of performance with the reported training of about 0.2-0.5 (in both better or worse directions) in mAP is not surprising.
